from typing import Literal, TypedDict

import sgg._typing as sgt

class Dict_Font(TypedDict):
    fg: sgt.ColorTypeN = ...
    family: str = ...
    font_size: int | float = 14
    weight: Literal["normal", "bold"] = ...
    slant: Literal["roman", "italic"] = ...
    underline: bool = ...
    overstrike: bool = ...
