from collections.abc import Iterator
from datetime import date,datetime
from typing import overload,Any
from ._time import times
__all__=['timeslist']
class timeslist:
 datelist:tuple[datetime|None]
 def __init__(
self,
dates:str|datetime|times|date|list|tuple,
format:str='%Y/%m/%d,%H:%M:%S'
)->None:...
 @classmethod
 def __instancecheck__(cls,ins:Any)->bool:...
 def __len__(self)->int:...
 def __iter__(self)->Iterator[datetime|None]:...
 @overload
 def __getitem__(self,val:int|slice)->Any|list:...
 @overload
 def __getitem__(self,val:int)->Any:...
 @overload
 def __getitem__(self,val:slice)->list:...
 def __dir__(self)->tuple[str,...]:...
 @overload
 def dir(self)->tuple[str,...]:...
 @overload
 @classmethod
 def dir(cls)->tuple[str,...]:...