from types import NotImplementedType
from typing import Any,Literal
from numpy import _ArrayT,ndarray
from numpy._typing import DTypeLike
from ..base import NPArray
__all__=['NPNumber']
class NPNumber(NPArray):
 data:ndarray
 def __init__(
self,
data:_ArrayT,
dtype:DTypeLike|None=None
)->None:...
 def __repr__(self)->str:...
 def __add__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __sub__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __mul__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __truediv__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 __radd__=__add__
 __rsub__=__sub__
 __rmul__=__mul__
 __rtruediv__=__truediv__
 def __mod__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __floordiv__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __pow__(self,other:int|float|ndarray|NPNumber)->NPNumber:...
 def __array_ufunc__(self,ufunc,method,*args,**kwargs)->NPNumber|Any|NotImplementedType:...
 @property
 def sum(self):...
 @property
 def median(self):...
 @property
 def var(self):...
 @property
 def max(self):...
 @property
 def min(self):...
 @property
 def mean(self):...
 @property
 def std(self):...
 @property
 def pow2(self):...
 def asum(self,axis:int|None=None,dtype:DTypeLike|None=None)->ndarray:...
 def amedian(self,axis:int|None=None)->ndarray:...
 def avar(self,axis:int|None=None,dtype:DTypeLike|None=None)->ndarray:...
 def amax(self,axis:int|None=None)->ndarray:...
 def amin(self,axis:int|None=None)->ndarray:...
 def amean(self,axis:int|None=None,dtype:DTypeLike|None=None)->ndarray:...
 def astd(self,axis:int|None=None,dtype:DTypeLike|None=None)->ndarray:...
 def amod(self,x)->ndarray:...
 def adivmod(self,x)->ndarray:...
 def apow(self,x)->ndarray:...
 def apow2(self)->ndarray:...
 def pow(self,x)->NPNumber:...
 def percentile(
self,
q:tuple[int,...],
axis:int|None=None,
method:Literal[
'inverted_cdf',
'averaged_inverted_cdf',
'closest_observation',
'interpolated_inverted_cdf',
'hazen',
'weibull',
'linear',
'median_unbiased',
'normal_unbiased'
]='linear'
)->ndarray:...
 def quantile(
self,
q:tuple[int,...],
axis:int|None=None,
method:Literal[
'inverted_cdf',
'averaged_inverted_cdf',
'closest_observation',
'interpolated_inverted_cdf',
'hazen',
'weibull',
'linear',
'median_unbiased',
'normal_unbiased'
]='linear'
)->ndarray:...
 def cussum(self)->NPNumber:'''一つ前の元の値との和を求める。'''
 def cumprod(self)->NPNumber:'''一つ前の元の値との積を求める。'''