from typing import Any, overload

import numpy as np

from sgg._typing import NDStr_

__all__ = ["_SET_OBJ"]

class _SET_OBJ:
    @overload
    def _to_str(self, s: str | np.str_) -> str: ...
    @overload
    def _to_str(self, s: Any) -> None: ...
    def _is_str(self, s: Any) -> bool: ...
    @overload
    def _to_number[value: int | np.integer](self, val: value) -> int: ...
    @overload
    def _to_number[value: float | np.floating](self, val: value) -> float: ...
    @overload
    def _to_number[value: complex | np.complexfloating](
        self, val: value
    ) -> complex: ...
    @overload
    def _to_number(self, val: Any) -> None: ...
    def _is_number(self, val: Any) -> bool: ...
    @overload
    def _to_real[value: int | np.integer](self, val: value) -> int: ...
    @overload
    def _to_real[value: float | np.floating](self, val: value) -> float: ...
    def _is_real(self, val: Any) -> bool: ...
    def _is_int(self, val: Any) -> bool: ...
    def _to_flat_list(self, array: list | tuple | range | np.ndarray) -> list[str]: ...
    def _to_str_flat_list(
        self, array: list | tuple | range | NDStr_ | str | np.str_
    ) -> list[str]: ...
    def _flatten(self,lst) -> list: ...