import numpy as np
from typing import overload
from numpy.polynomial import Polynomial
from ..npNumber import NPNumber
__all__=['NPStatistics']
class NPStatistics:
 x:np.ndarray
 y:np.ndarray
 data:np.ndarray
 @overload
 def __init__(
self,
data:NPNumber|np.ndarray=...
):...
 @overload
 def __init__(
self,
x:NPNumber|np.ndarray=...,
y:NPNumber|np.ndarray=...
):...
 def __repr__(self):...
 # x property
 @property
 def xsum(self):...
 @property
 def xave(self):...
 @property
 def xmin(self):...
 @property
 def xmax(self):...
 @property
 def xmean(self):...
 @property
 def xvar(self):...
 @property
 def xstd(self):...
 @property
 def xpow2(self):...
 @property
 def xdeviation(self):...
 @property
 def xlog(self):...
 @property
 def xlog10(self):...
 @property
 def xlog2(self):...
 @property
 def xlog1p(self):...
 @property
 def xdevsq(self):'''`x`の偏差平方和を求める。'''
 # y property
 @property
 def ysum(self):...
 @property
 def yave(self):...
 @property
 def ymin(self):...
 @property
 def ymay(self):...
 @property
 def ymean(self):...
 @property
 def yvar(self):...
 @property
 def ystd(self):...
 @property
 def ypow2(self):...
 @property
 def ydeviation(self):...
 @property
 def ylog(self):...
 @property
 def ylog10(self):...
 @property
 def ylog2(self):...
 @property
 def ylog1p(self):...
 @property
 def ydevsq(self):'''`y`の偏差平方和を求める。'''
 # data
 @property
 def sum(self):...
 @property
 def ave(self):...
 @property
 def min(self):...
 @property
 def may(self):...
 @property
 def mean(self):...
 @property
 def var(self):...
 @property
 def std(self):...
 @property
 def pow2(self):...
 @property
 def deviation(self):...
 @property
 def log(self):...
 @property
 def log10(self):...
 @property
 def log2(self):...
 @property
 def log1p(self):...
 @property
 def devsq(self):'''`data`の偏差平方和を求める。'''
 @property
 def CV(self):'''変動係数を求める。'''
 @property
 def n(self):'''`data`の長さの数値を返す。'''
 @property
 def n1(self):'''`data`の長さの数値-1の値を返す。'''
 def covariance(self):'''共分散を求める。'''
 def correlation(self):'''相関係数を求める。'''
 def correlation_coefficient(self):'''単相関係数を求める。'''
 # x,y
 @property
 def Sxxyy(self):'''`x`の偏差平方和と`y`の偏差平方和の積を求める。'''
 @property
 def Sxxyyroot(self):'''`x`の偏差平方和と`y`の偏差平方和の積の平方和を求める。'''
 # 回帰直線
 @overload
 def regression(
self,
n:int=1,
x:int|float|None=...
)->np.ndarray[np.float64,np.dtype[np.float64]]|np.float64:''''''
 @overload
 def regression(
self,
n:int=1
)->np.ndarray[np.float64,np.dtype[np.float64]]:'''点(x,y)に次数`n`の多項式を当てはめる。'''
 @overload
 def regression(
self,
n:int=1,
x:int|float=...
)->np.float64:'''点(x,y)に次数`n`の多項式の`x`の値を求める。'''