from test_data import *
if __name__=="__main__":
 layout=[
 [
  sgg.LineGraph(x=linex1,y=liney1,title="折り線グラフ"),
  sgg.Pie(data=piedata,title="円グラフ",label=pielabel)
 ],
 [
  sgg.BarGraph(x=bargraphx1,y=bargraphy1,title="縦軸棒グラフ",width=0.5),
  sgg.BarhGraph(x=bargraphx2,y=bargraphy2,title="横軸棒グラフ",height=0.5)
 ],
 [
  sgg.Scatter(x=scatterx1,y=scattery1,title="散布図"),
  sgg.Scatter(x=scatterx2,y=scattery2,title="散布図")
 ],
 [
  sgg.DScatter(x=dscatterx,y=dscattery,z=dscatterz,title="3D 散布図",zlabel=zlabel),
  sgg.Hist(data=histdata,title="ヒストグラフ")
 ],
 [
  sgg.Stem(x=stemx1,y=stemy1,title="ステムグラフ"),
  sgg.Boxplot(data=boxdata1,title="箱ひげ図",whis=1.5)
 ],
 [
  sgg.Waterfall(x=waterfallx,y=waterfally,width=0.5,title="ウォーターフォール",linestyle="dotted"),
  sgg.Waterfallh(x=waterfallx,y=waterfally,height=0.5,title="ウォーターフォール")
 ],
 [
  sgg.Step(data=stepdata,title="階段グラフ"),
  sgg.Stack(x=stackx,y=stacky,title="積み上げグラフ")
 ],
 [
  sgg.Eventplot(data=eventdata,linestyle="dashed",label=["a","b","c"],title="イベントグラフ"),
  sgg.Errorbar(x=errorbarx,y=errorbary,err=err,title="エラーバー")
 ],
 [
  sgg.Errorbar(x=errorbarx,y=errorbary,xerr=xerr,yerr=yerr,title="エラーバー"),
  sgg.Errorbar(x=errorbarx,y=errorbary,xerr=xerr,title="エラーバー")
 ],
 [
  sgg.Errorbar(x=errorbarx,y=errorbary,yerr=yerr,title="エラーバー"),
  sgg.Ecdf(data=ecdfdata,title="経験的累積分布関数のグラフ")
 ],
 [
  sgg.Hexbin(x=hexbinx1,y=hexbiny1,title="2次元六角形グラフ"),
  sgg.Funne(data=funnedata,title="じょうごグラフ")
 ],
 [
   sgg.Hist2d(x=hist2dx,y=hist2dy,title="2次元ヒストグラム"),
   sgg.Linefill(x=linefillx,ymax=linefillymax,ymin=linefillymin,title="積上げ面グラフ")
 ],
 [
   sgg.Stack(x=stackx,y=stacky,title="積み上げグラフ"),
   sgg.Violinplot(data=violindata,title="バイオリングラフ")
 ],
 [
   sgg.Stacked(data=stackeddata,dataname=stackeddataname,title="積み上げ縦棒グラフ"),
   sgg.Stackedh(data=stackeddata,dataname=stackeddataname,title="積み上げ横棒グラフ")
 ]
 ]
 win=sgg.window(title="デモ",layout=layout,scroll=True,maxmine=True)
 win.run()