from typing import Any,Iterator
from ..typing import Type_Numberlike
class Number:
 __static_attributes__:tuple[str]
 __class__:type
 __firstlineno__:int
 val:int|float
 def __init__(
self,
val:Type_Numberlike
)->None:'''数値に関するクラス

 :param val: 数値を指定する。
 :type val: Type_Numberlike
 :raises TypeError: `val`に数値以外を指定した場合に発生させる。'''
 def __dir__(self)->list[str]:...
 def __getattribute__(self,name:Any)->Any:...
 @classmethod
 def __instancecheck__(cls,ins)->bool:...
 def __int__(self)->int:...
 def __float__(self)->float:...
 def __str__(self)->str:...
 def __bool__(self)->bool:'''値が0以上ならTrueを,0未満ならFalseを返す。'''
 def __format__(self,format_spec:str)->str:...
 def format(self,format_spec:str)->str:...
 def __len__(self)->int:...
 def len(self)->int:...
 def types(self)->int|float:...
 def __add__(self,val:Type_Numberlike)->Number:...
 def __sub__(self,val:Type_Numberlike)->Number:...
 def __mul__(self,val:Type_Numberlike)->Number:...
 def __pow__(self,val:Type_Numberlike)->Number:...
 def __floordiv__(self,val:Type_Numberlike)->Number:...
 def __ipow__(self,val:Type_Numberlike)->Number:...
 def __truediv__(self,val:Type_Numberlike)->Number:...
 def __pow__(self,val:Type_Numberlike)->Number:...
 def __ipow__(self,val:Type_Numberlike)->Number:...
 def __radd__(self,val:Type_Numberlike)->Number:...
 def __rsub__(self,val:Type_Numberlike)->Number:...
 def __rmul__(self,val:Type_Numberlike)->Number:...
 def __rtruediv__(self,val:Type_Numberlike)->Number:...
 def __rmod__(self,val:Type_Numberlike)->Number:...
 def __rpow__(self,val:Type_Numberlike)->Number:...
 def __rfloordiv__(self,val:Type_Numberlike)->Number:...
 def __iadd__(self,val:Type_Numberlike)->Number:...
 def __isub__(self,val:Type_Numberlike)->Number:...
 def __imul__(self,val:Type_Numberlike)->Number:...
 def __itruediv__(self,val:Type_Numberlike)->Number:...
 def __eq__(self,val:Any)->bool:...
 def __ne__(self,val:Any)->bool:...
 def __lt__(self,val:Type_Numberlike)->bool:...
 def __le__(self,val:Type_Numberlike)->bool:...
 def __gt__(self,val:Type_Numberlike)->bool:...
 def __ge__(self,val:Type_Numberlike)->bool:...
 def __abs__(self)->Number:...
 def __round__(self,n:int=0)->Number:...
 def __ceil__(self)->Number:...
 def __floor__(self)->Number:...
 def __neg__(self)->Number:...
 def __pos__(self)->Number:...
 def value(self)->int|float:...
class LISTNumber:
 lists:list[int|float]|tuple[int|float]
 judge:bool
 def __init__(self,obj:list|tuple):'''一次元配列内のNumberを含む数値を数値に変換する。

 :param obj: 変換したい配列を指定する。
 :type obj: list|tuple'''
 def __bool__(self)->bool:'''配列内の全ての要素が数値のみTrueを返す。'''
 def __iter__(self)->Iterator[Any]:...
 def __len__(self)->int:...
 def __contains__(self,item:Any)->bool:...