from collections.abc import Iterator
from typing import Any,TypeAlias
from numpy import _DTypeT_co,ndarray
DType:TypeAlias=_DTypeT_co|None
class Datalist:
 data:ndarray
 def __init__(self,data:ndarray)->None:...
 def __iter__(self)->Iterator[Any]:...
 def __len__(self)->int:...
 @property
 def ndim(self)->int:...
 @property
 def shape(self)->tuple[int,...]:...
 @property
 def size(self)->int:...
 @property
 def T(self)->ndarray:...
class Manylist(Datalist):
 def __init__(self,data:list|tuple|ndarray,dtype:DType=None):...
class Onelist(Datalist):
 def __init__(self,data:list|tuple|ndarray,dtype:DType=None):...