'''グラフの線を設定するモジュール'''
from ....nparray import NPArray
from ...typing import Type_Solid

__all__=['Solid','Solidlist']
class Solid:
 def __init__(self,solid:Type_Solid='-')->None:...
 @property
 def solid(self)->str:...
class Solidlist(NPArray):
 data:NPArray
 def __init__(
self,
solid:Type_Solid='-',
)->None:...
 def __iter__(self):...
 def __str__(self)->str:...
 def __getitem__(self,key:int):...
 def __repr__(self)->str:...