"""numpyのdtypeに関するモジュール"""

from typing import Any

__all__ = [
    "boolDtype",
    "complexDtype",
    "floatDtype",
    "intDtype",
    "integerDtype",
    "numberDtype",
    "strDtype",
    "uintDtype",
]

def boolDtype(obj: Any) -> bool: ...
def complexDtype(obj: Any) -> bool: ...
def floatDtype(obj: Any) -> bool: ...
def intDtype(obj: Any) -> bool: ...
def integerDtype(obj: Any) -> bool: ...
def numberDtype(obj: Any) -> bool: ...
def uintDtype(obj: Any) -> bool: ...
def strDtype(obj: Any) -> bool: ...
