from collections.abc import Iterator
from ....typing import ndarray,Any,nListlike
from numpy._typing import DTypeLike
__all__=['Manylist','Onelist']
class Datalist:
 data:ndarray
 def __init__(self,data:ndarray)->None:...
 def __iter__(self)->Iterator[Any]:...
 def __len__(self)->int:...
 @property
 def ndim(self)->int:...
 @property
 def shape(self)->tuple[int,...]:...
 @property
 def size(self)->int:...
 @property
 def T(self)->ndarray:...
class Manylist(Datalist):
 def __init__(self,data:nListlike,dtype:DTypeLike|None=None):...
class Onelist(Datalist):
 def __init__(self,data:nListlike,dtype:DTypeLike|None=None):...