from .element import Element

__all__ = ["TElement"]

class TElement(Element):
    style_list: list[str] = ...
    stylename: str = ...
    def _padding(self, *args): ...
    def _unit_change(self, val): ...
