"""フレームワークやプログラムのテスト用の値を保存するモジュール"""

from ._dtype import *
from ._timezone import testing_timezone

__all__ = [
    "testing_BoolCodes",
    "testing_BytesCodes",
    "testing_CharacterCodes",
    "testing_CLongDoubleCodes",
    "testing_Complex128Codes",
    "testing_Complex64Codes",
    "testing_ComplexFloatingCodes",
    "testing_DT64Codes",
    "testing_DT64Codes_any",
    "testing_DT64Codes_date",
    "testing_DT64Codes_datetime",
    "testing_DT64Codes_int",
    "testing_FlexibleCodes",
    "testing_Float16Codes",
    "testing_Float32Codes",
    "testing_Float64Codes",
    "testing_FloatingCodes",
    "testing_GenericCodes",
    "testing_InexactCodes",
    "testing_Int16Codes",
    "testing_Int32Codes",
    "testing_Int64Codes",
    "testing_Int8Codes",
    "testing_IntCCodes",
    "testing_IntegerCodes",
    "testing_IntPCodes",
    "testing_LongCodes",
    "testing_LongDoubleCodes",
    "testing_LongLongCodes",
    "testing_NumberCodes",
    "testing_ObjectCodes",
    "testing_SignedIntegerCodes",
    "testing_StrCodes",
    "testing_StringCodes",
    "testing_TD64Codes",
    "testing_TD64Codes_any",
    "testing_TD64Codes_int",
    "testing_TD64Codes_timedelta",
    "testing_timezone",
    "testing_UInt16Codes",
    "testing_UInt32Codes",
    "testing_UInt64Codes",
    "testing_UInt8Codes",
    "testing_UIntCCodes",
    "testing_UIntPCodes",
    "testing_ULongCodes",
    "testing_ULongLongCodes",
    "testing_UnsignedIntegerCodes",
    "testing_VoidCodes",
]
